## ­Ъћј­Ъћј­Ъћј

 

- **рЃЊрЃўрЃарЃћрЃЦрЃбрЃЮрЃарЃўрЃљ (paths)** Рєњ рЃњрЃљрЃЏрЃЮрЃўрЃДрЃћрЃюрЃћ `r"path"` рЃљрЃю рЃЮрЃарЃЏрЃљрЃњрЃў `\`

!!!info
    рЃњрЃљрЃЊрЃљрЃ«рЃћрЃЊрЃћ рЃЎрЃўрЃЊрЃћрЃЋ рЃћрЃарЃЌрЃ«рЃћрЃџ рЃњрЃљрЃюрЃЏрЃљрЃарЃбрЃћрЃЉрЃћрЃЉрЃерЃў "рЃЊрЃљрЃ«рЃарЃўрЃџрЃў рЃ«рЃљрЃќрЃў" рЃўрЃњрЃўрЃЋрЃћ "Python-рЃерЃў рЃЊрЃўрЃарЃћрЃЦрЃбрЃЮрЃарЃўрЃћрЃЉрЃўрЃА рЃАрЃгрЃЮрЃарЃљрЃЊ рЃЕрЃљрЃгрЃћрЃарЃљ" - рЃА.


- **EOL while scanning string** Рєњ рЃцрЃљрЃўрЃџрЃўрЃА рЃЊрЃўрЃарЃћрЃЦрЃбрЃЮрЃарЃўрЃўрЃА рЃЏрЃўрЃАрЃљрЃЏрЃљрЃарЃЌрЃА рЃљрЃЎрЃџрЃўрЃљ рЃЉрЃарЃГрЃДрЃљрЃџрЃў `"`.  
EOL means end of line, and the message means that Python reached the end of the line of code while processing the string on line 2. The path string needs another quotation mark to finish it. 
- **QVariant.Int** Рєњ **AttributeError: type object 'QVariant' has no attribute 'int'** Рєњ рЃърЃљрЃбрЃљрЃарЃљ `i` рЃерЃћрЃфрЃЊрЃЮрЃЏрЃљрЃљ, рЃАрЃгрЃЮрЃарЃўрЃљ `Int`.

- **Missing functions in IDE** Рєњ рЃЌрЃБ рЃцрЃБрЃюрЃЦрЃфрЃўрЃћрЃЉрЃў рЃљрЃа рЃЕрЃљрЃюрЃА, рЃЏрЃљрЃерЃўрЃю qgis рЃЏрЃЮрЃЊрЃБрЃџрЃў рЃБрЃюрЃЊрЃљ рЃерЃћрЃЏрЃЮрЃўрЃбрЃљрЃюрЃЮ рЃЎрЃЮрЃЊрЃўрЃА рЃЊрЃљрЃАрЃљрЃгрЃДрЃўрЃАрЃерЃў. 

```py title="Missing_functions_in_IDE.py" linenums="1"
import qgis

#рЃЎрЃЮрЃЊрЃўрЃА рЃЊрЃљрЃюрЃљрЃарЃЕрЃћрЃюрЃў рЃюрЃљрЃгрЃўрЃџрЃў рЃЌрЃћрЃЏрЃљрЃбрЃБрЃарЃљрЃЊ
```

---

- **TEMPORARY_OUTPUT** Рєњ рЃЊрЃарЃЮрЃћрЃЉрЃўрЃЌрЃў рЃерЃћрЃЊрЃћрЃњрЃў, рЃЌрЃБ рЃњрЃЋрЃўрЃюрЃЊрЃљ рЃцрЃљрЃўрЃџрЃљрЃЊ рЃерЃћрЃЋрЃўрЃюрЃљрЃ«рЃЮрЃЌ Рєњ рЃЕрЃљрЃЋрЃљрЃюрЃљрЃфрЃЋрЃџрЃЮрЃЌ `output`
!!!warning
    рЃАрЃ«рЃЋрЃљ рЃерЃћрЃЏрЃЌрЃ«рЃЋрЃћрЃЋрЃљрЃерЃў рЃърЃарЃЮрЃњрЃарЃљрЃЏрЃўрЃА рЃЊрЃљрЃ«рЃБрЃарЃЋрЃўрЃА рЃерЃћрЃЏрЃЊрЃћрЃњ рЃЏрЃўрЃдрЃћрЃЉрЃБрЃџрЃў рЃерЃћрЃЊрЃћрЃњрЃћрЃЉрЃў рЃЊрЃљрЃўрЃЎрЃљрЃарЃњрЃћрЃЉрЃљ.



    layers = QgsProject.instance().mapLayersByName('sadguri')

layer = layers[0]

delf = layer.dataProvider().capabilities()

feats = layer.getFeatures()

dfeats = []



рЃЎрЃЮрЃЊрЃўрЃА рЃюрЃљрЃгрЃўрЃџрЃўрЃљ рЃгрЃљрЃарЃЏрЃЮрЃЊрЃњрЃћрЃюрЃўрЃџрЃў рЃЊрЃљ рЃЌрЃБ рЃерЃћрЃфрЃЊрЃЮрЃЏрЃљрЃА рЃљрЃњрЃЊрЃћрЃЉрЃА

>>>>
IndexError: list index out of range
рЃюрЃўрЃерЃюрЃљрЃЋрЃА рЃарЃЮрЃЏ mapLayersByName('sadguri') рЃАрЃљрЃ«рЃћрЃџрЃў рЃерЃарЃўрЃА рЃљрЃа рЃњрЃљрЃЦрЃЋрЃА рЃерЃћрЃфрЃЋрЃџрЃўрЃџрЃў рЃЊрЃљ рЃЋрЃћрЃа рЃ«рЃЋрЃЊрЃћрЃЉрЃљ.


--

out = r'C:\Users\Public\GIS\PyGK\tema_4_1\Georgia_municipalities2.shp'

processing.run("native:deletecolumn", {INPUT': layer,\


'COLUMN':['SHAPE_Leng'],'OUTPUT':out})


EOL while scanning string literal

рЃерЃћрЃфрЃЊрЃЮрЃЏрЃљ рЃюрЃўрЃерЃюрЃљрЃЋрЃА рЃарЃЮрЃЏ 'INPUT':  - рЃА рЃљрЃЎрЃџрЃўрЃљ ' рЃфрЃљрЃџ рЃЏрЃ«рЃљрЃарЃћрЃА


layer = layes[0]


NameError: name 'layes' is not defined

layes рЃљрЃЎрЃџрЃўрЃљ r    - layers


proces sing.run("native:deleteduplicategeometries", {'INPUT':layer,'OUTPUT':output})

invalid syntax рЃерЃћрЃфрЃЊрЃЮрЃЏрЃљ proces sing.run рЃћрЃарЃЌрЃљрЃЊ рЃБрЃюрЃЊрЃљ рЃћрЃгрЃћрЃарЃЮрЃА processing.run


рЃАрЃЋрЃћрЃбрЃў рЃарЃЮрЃЏрЃћрЃџрЃАрЃљрЃф рЃАрЃЎрЃарЃўрЃърЃбрЃў рЃћрЃФрЃћрЃЉрЃА рЃљрЃбрЃарЃўрЃЉрЃБрЃбрЃБрЃџ рЃфрЃ«рЃарЃўрЃџрЃерЃў рЃцрЃўрЃќрЃўрЃЎрЃБрЃарЃљрЃЊ рЃљрЃа рЃљрЃарЃАрЃћрЃЉрЃЮрЃЉрЃА...

рЃљрЃЏ рЃерЃћрЃЏрЃЌрЃ«рЃЋрЃћрЃЋрЃљрЃерЃў рЃћрЃА рЃљрЃарЃўрЃА fid рЃАрЃЋрЃћрЃбрЃў.

Traceback (most recent call last):

  File "<input>", line 1, in <module>

  File "<string>", line 15, in <module>

KeyError: 'fid'